#多环境开发
spring:
  profiles:
    active: test2
---
spring:
  profiles: test1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root
    password: bitware
  main:
    banner-mode: off


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      table-prefix: tbl_

---
spring:
  profiles: test2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root
    password: '0214'
  main:
    banner-mode: off

#mp日志，logimpl开启mysql语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      table-prefix: tbl_
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 0
      logic-not-delete-value: 1