server:
  port: 80
spring:
#  datasource:
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
#      username: root
#      password: 0214
  cache:
    type: redis
    redis:
      use-key-prefix: true
      key-prefix: study_
      time-to-live: 50s
      cache-null-values: true
  redis:
    host: localhost
    port: 6379





