spring:
  task:
    scheduling:
      pool:
        size: 1                           #??????? ??1
      thread-name-prefix: ssm_            #???????? ?? scheduling-
      shutdown:
        await-termination: false          #??????????????
        await-termination-period: 10s     #??????????????????????
