server:
  port: 80
spring:
#  datasource:
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
#      username: root
#      password: 0214
  cache:
    type: ehcache
    ehcache:
      config: ehcache.xml



