server:
  port: 80
spring:
  boot:
    admin:
      client:
        url: http://localhost:8080
management:
  #对外是否开放
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  #开启info端点
  info:
    env:
      enabled: true
#info端点配置
info:
  appName: @project.artifactId@
  vaersion: @project.version@
  company: itheima
  author: zhuangbl
